### ISSUE TITLE
Need to set default project  for evergreen patch builds

### ISSUE THREAD

**Issue by IanWhalen** [mongodb/server-workflow-tool#11]
The following needs to get appended to  .evergreen.yml somewhere in this script:

```
projects:
- name: mongodb-mongo-master
  default: true
  alias: required
  tasks:
  - all
```
